package LavaKirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LavaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.31 13:54:23 // Generated by ComTest
 *
 */
public class EsiintyjaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi61 */
  @Test
  public void testRekisteroi61() {    // Esiintyja: 61
    Esiintyja esi1 = new Esiintyja(); 
    assertEquals("From: Esiintyja line: 63", 0, esi1.getTunnusNro()); 
    esi1.rekisteroi(); 
    Esiintyja esi2 = new Esiintyja(); 
    esi2.rekisteroi(); 
    int n1 = esi1.getTunnusNro(); 
    int n2 = esi2.getTunnusNro(); 
    assertEquals("From: Esiintyja line: 69", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro81 */
  @Test
  public void testGetTunnusNro81() {    // Esiintyja: 81
    Esiintyja esi1 = new Esiintyja(); 
    esi1.vastaaEsiintyja("Metallica"); 
    assertEquals("From: Esiintyja line: 84", 5, esi1.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi94 */
  @Test
  public void testGetNimi94() {    // Esiintyja: 94
    Esiintyja esi1 = new Esiintyja(); 
    esi1.vastaaEsiintyja("Metallica"); 
    assertEquals("From: Esiintyja line: 97", "Metallica", esi1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone181 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone181() throws CloneNotSupportedException {    // Esiintyja: 181
    Esiintyja esi = new Esiintyja(); 
    esi.parse("   2   | Metallica "); 
    Esiintyja kopio = esi.clone(); 
    assertEquals("From: Esiintyja line: 186", esi.toString(), kopio.toString()); 
    esi.parse("   1   |  Metallica "); 
    assertEquals("From: Esiintyja line: 188", false, kopio.toString().equals(esi.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse199 */
  @Test
  public void testParse199() {    // Esiintyja: 199
    Esiintyja esi = new Esiintyja(); 
    esi.parse("   2   |  Metallica "); 
    assertEquals("From: Esiintyja line: 202", "2|Metallica", esi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString216 */
  @Test
  public void testToString216() {    // Esiintyja: 216
    Esiintyja esi = new Esiintyja(); 
    esi.parse("   2   |Metallica"); 
    assertEquals("From: Esiintyja line: 219", "2|Metallica", esi.toString()); 
  } // Generated by ComTest END
}