package LavaKirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LavaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.31 13:55:27 // Generated by ComTest
 *
 */
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi82 */
  @Test
  public void testRekisteroi82() {    // Paiva: 82
    Paiva paiva1 = new Paiva(); 
    assertEquals("From: Paiva line: 84", 0, paiva1.getTunnusNro()); 
    paiva1.rekisteroi(); 
    Paiva paiva2 = new Paiva(); 
    paiva2.rekisteroi(); 
    int n1 = paiva1.getTunnusNro(); 
    int n2 = paiva2.getTunnusNro(); 
    assertEquals("From: Paiva line: 90", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro103 */
  @Test
  public void testGetTunnusNro103() {    // Paiva: 103
    Paiva paiva = new Paiva(); 
    paiva.rekisteroi(); 
    assertEquals("From: Paiva line: 106", 6, paiva.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLiput132 */
  @Test
  public void testGetLiput132() {    // Paiva: 132
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 135", 100, paiva.getLiput()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetEtuLiput145 */
  @Test
  public void testGetEtuLiput145() {    // Paiva: 145
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 148", 150, paiva.getEtuLiput()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetBaariTulot158 */
  @Test
  public void testGetBaariTulot158() {    // Paiva: 158
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 161", 1500, paiva.getBaariTulot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKioskiTulot171 */
  @Test
  public void testGetKioskiTulot171() {    // Paiva: 171
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 174", 1000, paiva.getKioskiTulot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMenot184 */
  @Test
  public void testGetMenot184() {    // Paiva: 184
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 187", 2000, paiva.getMenot()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetIlmaisLiput197 */
  @Test
  public void testGetIlmaisLiput197() {    // Paiva: 197
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 200", 15, paiva.getIlmaisLiput()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPohjaKassa210 */
  @Test
  public void testGetPohjaKassa210() {    // Paiva: 210
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 213", 700, paiva.getPohjaKassa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetEsiintyja223 */
  @Test
  public void testGetEsiintyja223() {    // Paiva: 223
    Paiva paiva = new Paiva(); 
    paiva.vastaaPaivan(); 
    assertEquals("From: Paiva line: 226", 500, paiva.getEsiintyja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString235 */
  @Test
  public void testToString235() {    // Paiva: 235
    Paiva paiva = new Paiva(); 
    paiva.parse("   3  |  10.3.1996   | 0|0|0|0|0|0|0"); 
    assertEquals("From: Paiva line: 238", true, paiva.toString().startsWith("3|10.3.1996|0|"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse257 */
  @Test
  public void testParse257() {    // Paiva: 257
    Paiva paiva = new Paiva(); 
    paiva.parse("0|10.3.1996|0|0|0|0|0|0|0"); 
    assertEquals("From: Paiva line: 260", 0, paiva.getTunnusNro()); 
    assertEquals("From: Paiva line: 261", true, paiva.toString().startsWith("0|10.3.1996|0|0|0|0|0|0|0")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone412 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone412() throws CloneNotSupportedException {    // Paiva: 412
    Paiva paiva = new Paiva(); 
    paiva.parse("  0  |  10.3.1996   |0|0|0|0|0|0|0"); 
    Paiva kopio = paiva.clone(); 
    assertEquals("From: Paiva line: 417", paiva.toString(), kopio.toString()); 
    paiva.parse("   0  |  10.3.1996   |1|0|0|0|0|0|0"); 
    assertEquals("From: Paiva line: 419", false, kopio.toString().equals(paiva.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals435 */
  @Test
  public void testEquals435() {    // Paiva: 435
    Paiva paiva1 = new Paiva(); 
    paiva1.parse("   0  | 10.3.1996 | 0|0|0|0|0|0|0"); 
    Paiva paiva2 = new Paiva(); 
    paiva2.parse("   0  | 10.3.1996 | 0|0|0|0|0|0|0"); 
    Paiva paiva3 = new Paiva(); 
    paiva3.parse("   0  | 10.3.1996 | 1|0|0|0|0|0|0"); 
    assertEquals("From: Paiva line: 443", true, paiva1.equals(paiva2)); 
    assertEquals("From: Paiva line: 444", true, paiva2.equals(paiva1)); 
    assertEquals("From: Paiva line: 445", false, paiva1.equals(paiva3)); 
    assertEquals("From: Paiva line: 446", false, paiva3.equals(paiva2)); 
  } // Generated by ComTest END
}