package LavaKirja;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import LavaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.27 14:36:49 // Generated by ComTest
 *
 */
public class RelaatioTest {



  // Generated by ComTest BEGIN
  /** testToString57 */
  @Test
  public void testToString57() {    // Relaatio: 57
    Relaatio rela = new Relaatio(1,1); 
    rela.parse("   1  |  1   |1 "); 
    assertEquals("From: Relaatio line: 60", true, rela.toString().startsWith("1|1|1")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi86 */
  @Test
  public void testRekisteroi86() {    // Relaatio: 86
    Relaatio rela1 = new Relaatio(); 
    assertEquals("From: Relaatio line: 88", 0, rela1.getTunnusNro()); 
    rela1.rekisteroi(); 
    Relaatio rela2 = new Relaatio(); 
    rela2.rekisteroi(); 
    int n1 = rela1.getTunnusNro(); 
    int n2 = rela2.getTunnusNro(); 
    assertEquals("From: Relaatio line: 94", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro106 */
  @Test
  public void testGetTunnusNro106() {    // Relaatio: 106
    Relaatio rela = new Relaatio(); 
    rela.rekisteroi(); 
    assertEquals("From: Relaatio line: 109", 3, rela.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetpId119 */
  @Test
  public void testGetpId119() {    // Relaatio: 119
    Relaatio rela = new Relaatio(1, 1); 
    assertEquals("From: Relaatio line: 121", 1, rela.getpId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGeteId131 */
  @Test
  public void testGeteId131() {    // Relaatio: 131
    Relaatio rela = new Relaatio(1, 1); 
    assertEquals("From: Relaatio line: 133", 1, rela.geteId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse143 */
  @Test
  public void testParse143() {    // Relaatio: 143
    Relaatio rela = new Relaatio(); 
    rela.parse("0|1|1 "); 
    assertEquals("From: Relaatio line: 146", true, rela.toString().startsWith("0|1|1")); 
  } // Generated by ComTest END
}